import "@/app/globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <main className="purple-dark text-foreground bg-background">
            <Navbar></Navbar>
            {children}
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
